### PR TITLE
fixed captcha race condition on load

### LINKED ISSUE #242: Race condition (?) when loading Recaptcha in the web faucet
Seems like there is a race condition when loading Recaptcha.

It appears when opening the faucet in Firefox.

To reproduce:

1. Start the app

```
cd client
export PUBLIC_FAUCET_URL="https://example.com/test"      
export PUBLIC_CAPTCHA_KEY="6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
npm run build && npm run preview 
```

2. Open the site in Firefox

3. Reload the page without cache a couple of times.

Sometimes, the captcha does not load.
Sometimes without any error, sometimes with `TypeError: window.grecaptcha.render is not a function`

cc @Bullrich

### PR DESCRIPTION
**Pull request by Bullrich**
This closes #242

There was a race condition where sometimes the script of the captcha component hasn't loaded on time and it was causing a runtime error.

This commit modifies the code so that all the window methods are set first, and then the script tag is imported, this way we know that the required environment for the captcha is correctly set up.

### CODE REVIEW

File: client/src/lib/components/CaptchaV2.svelte [hunk 1]
```diff
@@ -6,20 +6,25 @@
...
-		if (window.grecaptcha) {
+	onMount(() => {
+		window.captchaLoaded = () => {
+			const darkTheme =
+				window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches;
+			const mobileScreen = window.innerHeight > window.innerWidth;
+
+			if (!window.grecaptcha) {
+				throw new Error("grecaptcha is undefined!");
+			}
```
Comment (Bullrich) [inline client/src/lib/components/CaptchaV2.svelte:19]: Should we force the browser to reload the page if this happen?

Comment (mutantcornholio) [reply client/src/lib/components/CaptchaV2.svelte:19]: I wouldn't go down that road, to avoid infinite reloads.

**Review by mutantcornholio — APPROVED** [review]
